version: "3.8"

services:
  mysql:
    image: mysql:8

    container_name: ai_mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aiapp

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend

    container_name: ai_backend

    restart: always

    ports:
      - "8080:8080"

    depends_on:
      - mysql

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/aiapp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      GROQ_API_KEY: ${GROQ_API_KEY}
      

  frontend:
    build: ./frontend

    container_name: ai_frontend

    restart: always

    ports:
      - "5173:5173"

    depends_on:
      - backend

volumes:
  mysql_data:
